// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package queries

import (
	"context"
	"database/sql"
)

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (sql.Result, error) {
	return q.exec(ctx, q.deleteUserStmt, deleteUser, id)
}

const storeUser = `-- name: StoreUser :execresult
INSERT INTO users (first_name, email, password, role_id) VALUES (?, ?, ?, ?)
`

type StoreUserParams struct {
	FirstName string         `json:"first_name"`
	Email     sql.NullString `json:"email"`
	Password  string         `json:"password"`
	RoleID    int32          `json:"role_id"`
}

func (q *Queries) StoreUser(ctx context.Context, arg StoreUserParams) (sql.Result, error) {
	return q.exec(ctx, q.storeUserStmt, storeUser,
		arg.FirstName,
		arg.Email,
		arg.Password,
		arg.RoleID,
	)
}
