// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
	"time"
)

type Role struct {
	ID    int32  `json:"id"`
	Alias string `json:"alias"`
}

type Task struct {
	ID          int32         `json:"id"`
	UserID      int32         `json:"user_id"`
	Summary     string        `json:"summary"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	UpdatedBy   int32         `json:"updated_by"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
	DeletedBy   sql.NullInt32 `json:"deleted_by"`
	IsDone      bool          `json:"is_done"`
	PerformedAt sql.NullTime  `json:"performed_at"`
}

type User struct {
	ID        int32          `json:"id"`
	FirstName string         `json:"first_name"`
	Email     sql.NullString `json:"email"`
	Password  string         `json:"password"`
	RoleID    int32          `json:"role_id"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
