// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.sql

package queries

import (
	"context"
	"database/sql"
)

const storeRole = `-- name: StoreRole :execresult
INSERT INTO roles (id,alias) VALUES (?,?)
`

type StoreRoleParams struct {
	ID    int32  `json:"id"`
	Alias string `json:"alias"`
}

func (q *Queries) StoreRole(ctx context.Context, arg StoreRoleParams) (sql.Result, error) {
	return q.exec(ctx, q.storeRoleStmt, storeRole, arg.ID, arg.Alias)
}
